esphome:
  name: esp32-c3-bt-proxy
  platformio_options:
    board_build.flash_mode: dio
  includes:
    - lora_handler.h
  on_boot:
    priority: -10
    then:
      - lambda: |-
          auto *my_lora = new LoRaCustomComponent();
          App.register_component(my_lora); 

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  # Для Bluetooth и прямой работы с SPI на C3 нужен esp-idf
  framework:
    type: esp-idf

# Подключаем пакет Bluetooth Proxy
packages:
  remote_package:
    url: https://github.com/esphome/bluetooth-proxies
    files: [esp32-generic/esp32-generic-c3.yaml]
    ref: main

wifi:
  ssid: "ASUS_W"
  password: "whiteWOLF667djkr"
  # Важно для стабильности радиомодулей
  power_save_mode: none

# Настройка MQTT (обязательна для работы Discovery в C++ коде)
mqtt:
  broker: 192.168.1.64  # IP адрес вашего MQTT брокера (Home Assistant)
  username: "sergey_vash"
  password: "vash_sa"
  # Отключаем встроенный discovery самого моста, так как мы 
  # вручную шлем конфиги для LoRa датчиков из кода
  discovery: false 

# Активируем API и OTA для управления
api:
ota:

# Логгер для отладки LoRa в консоли
logger:
  level: DEBUG
