esphome:
  name: esphome-web-cdf5a4

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

wifi:
  ssid: "ASUS_W"                # <-- Замените на ваш Wi-Fi, если имя другое
  password: "whiteWOLF667djkr"  # <-- Замените на ваш пароль от Wi-Fi
  fast_connect: true
  power_save_mode: NONE

# Включаем шину I2S звука для Supermini
i2s_audio:
  - id: i2s_input_bus
    i2s_bclk_pin: GPIO4    # MIC_SCK (контакт 4)
    i2s_lrclk_pin: GPIO5   # MIC_WS  (контакт 5)

microphone:
  - platform: i2s_audio
    id: board_microphone
    i2s_audio_id: i2s_input_bus
    i2s_din_pin: GPIO6     # MIC_SD  (контакт 6)
    adc_type: external     
    pdm: false
    bits_per_sample: 32bit      
    sample_rate: 16000     # КРИТИЧЕСКИ ВАЖНО: частота для голосового ассистента HA

# Привязка встроенной кнопки BOOT с подтяжкой питания
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode: INPUT_PULLUP
      ignore_strapping_warning: true 
    name: "Кнопка Ассистента"
    on_press:
      - voice_assistant.start:

# Подключение к голосовому движку Home Assistant с обработкой звука
voice_assistant:
  id: va
  microphone: board_microphone
  noise_suppression_level: 3   # Агрессивное подавление шумов (максимум)
  auto_gain: 24.0dBFS          # Автоматическое выравнивание громкости голоса
  volume_multiplier: 1.5       # Дополнительное общее усиление микрофона в 1.5 раза

# Обязательные компоненты для интеграции с Home Assistant
api:
logger:
