esphome:
  name: esphome-web-cdf5a4

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

wifi:
  ssid: "ASUS_W"
  password: "whiteWOLF667djkr"
  fast_connect: true
  power_save_mode: NONE

# Включаем шину I2S звука для Supermini
i2s_audio:
  - id: i2s_input_bus
    i2s_bclk_pin: GPIO4    # MIC_SCK (контакт 4)
    i2s_lrclk_pin: GPIO5   # MIC_WS  (контакт 5)

microphone:
  - platform: i2s_audio
    id: board_microphone
    i2s_audio_id: i2s_input_bus
    i2s_din_pin: GPIO6     # MIC_SD  (контакт 6)
    adc_type: external     # <--- ДОБАВЬТЕ ЭТУ СТРОКУ
    pdm: false
    bits_per_sample: 32bit      
    
# Привязка встроенной кнопки BOOT с подтяжкой питания
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode: INPUT_PULLUP
      ignore_strapping_warning: true # Глушим предупреждение компилятора про strapping pin
    name: "Кнопка"
    on_press:
      - voice_assistant.start:

# Подключение к голосовому движку Home Assistant
voice_assistant:
  id: va
  microphone: board_microphone
  noise_suppression_level: 3   # ИСПРАВЛЕНО: подняли до 3 для лучшей фильтрации
  auto_gain: 20.0dBFS          # ИСПРАВЛЕНО: строго float-формат '24.0dBFS' большими буквами
  volume_multiplier: 1.5       # Чуть снизили, чтобы не было перегруза при 24dBFS
  # --- ДОБАВЬТЕ ЭТИ СТРОКИ ---
  max_listen_duration: 10s       # Ассистент принудительно выключится через 10 секунд, даже если вы молчите
  silence_detection: true        # Включаем автоматическое определение конца фразы

api:
logger:
