name: Compile ESPHome

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build ESPHome Binary
        uses: esphome/build-action@v5
        with:
          yaml_file: bt.yaml
          version: latest
          cache: false  # ПРИНУДИТЕЛЬНО ОТКЛЮЧАЕМ КЕШ, чтобы обойти ошибку

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: esp32-c3-binary
          path: .esphome/build/bt/.pioenvs/*/firmware.bin
