name: Compile ESPHome

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build ESPHome Binary
        uses: esphome/build-action@v6  # Обновил до v6
        with:
          yaml_file: bt.yaml
          version: latest
          
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: esp32-c3-binary
          path: .esphome/build/*/checkout/.pioenvs/*/firmware.bin
